services:
  Mooc.Users.domain.UserRepository:
    class: ../../../../../Contexts/Mooc/Users/infrastructure/persistence/MongoUserRepository
    arguments: ["@Mooc.ConnectionManager"]

  Mooc.Users.application.SingUpUser:
    class: ../../../../../Contexts/Mooc/Users/application/SingUpUser
    arguments: ["@Mooc.Users.domain.UserRepository"]
  
  Mooc.Users.application.SingInUser:
    class: ../../../../../Contexts/Mooc/Users/application/SingInUser
    arguments: ["@Mooc.Users.domain.UserRepository"]
